### ISSUE TITLE
TemplateNotFound: loopify.html

### ISSUE THREAD

**Issue by bjorn3** [hdc-arizona/cfgexplorer#1]
```
$ export FLASK_APP=looper.py
$ python3 -m flask run
 * Serving Flask app "looper"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2018-05-22 18:30:06,766] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bjorn/Documenten/cfgexplorer/looper.py", line 16, in looper
    return render_template('loopify.html')
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: loopify.html
127.0.0.1 - - [22/May/2018 18:30:06] "GET / HTTP/1.1" 500 -
[2018-05-22 18:30:07,139] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bjorn/Documenten/cfgexplorer/looper.py", line 16, in looper
    return render_template('loopify.html')
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: loopify.html
127.0.0.1 - - [22/May/2018 18:30:07] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [22/May/2018 18:30:07] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [22/May/2018 18:30:07] "GET /favicon.ico HTTP/1.1" 404 -
```

**Comment by devkotasabin** [comment]
The URL for CFGExplorer is `http://localhost:5000/tracevis/`. Could you try this URL?
Currently, the URL `http://127.0.0.1:5000/` or `http://localhost:5000/` is unused. Thanks.

**Comment by devkotasabin** [comment]
I have now added the URLs `http://localhost:5000/` and `http://localhost:5000/cfgexplorer/` for the app. So you can use any of the above three URLs.

**Comment by bjorn3** [comment]
It works!
